### ISSUE TITLE
Are updates planned?

### ISSUE THREAD

**Issue by yayamamo** [tsproisl/Pareidoscope#1]
I cloned the latest UD_English-EWT, and converted `en_ewt-ud-train.conllu` into a SQLite db.
Then, I tried the query `ex_association_two_structures.json` as mentioned in the README as follows:
`pareidoscope_association_strength --format db -o associations en-ud-train.db ex_association_two_structures.json`, but I encountered the "float division by zero" error as follows:
```
INFO 2022-10-04 17:13:08,334: Using 3 + 1 processes
INFO 2022-10-04 17:13:08,334: query no. 0
INFO 2022-10-04 17:13:11,559: {'embeddings': {'o11': 182, 'r1': 303.0, 'c1': 3996.0, 'n': 7584, 'inconsistent': 0}, 'subgraphs': {'o11': 182, 'r1': 303.0, 'c1': 3996.0, 'n': 7584, 'inconsistent': 0}, 'focus_points': {'o11': 179, 'r1': 284.0, 'c1': 3930.0, 'n': 7122, 'inconsistent': 0}, 'sentences': {'o11': 176, 'r1': 264.0, 'c1': 3178.0, 'n': 5153, 'inconsistent': 26}}
INFO 2022-10-04 17:13:11,559: query no. 1
INFO 2022-10-04 17:13:15,007: {'embeddings': {'o11': 6, 'r1': 1306.0, 'c1': 68.0, 'n': 22288, 'inconsistent': 0}, 'subgraphs': {'o11': 6, 'r1': 1306.0, 'c1': 68.0, 'n': 22288, 'inconsistent': 0}, 'focus_points': {'o11': 6, 'r1': 1306.0, 'c1': 68.0, 'n': 22288, 'inconsistent': 0}, 'sentences': {'o11': 6, 'r1': 1118.0, 'c1': 62.0, 'n': 9136, 'inconsistent': 10}}
INFO 2022-10-04 17:13:15,007: query no. 2
INFO 2022-10-04 17:13:19,327: {'embeddings': {'o11': 122, 'r1': 250.0, 'c1': 237.0, 'n': 22884, 'inconsistent': 0}, 'subgraphs': {'o11': 122, 'r1': 250.0, 'c1': 237.0, 'n': 22884, 'inconsistent': 0}, 'focus_points': {'o11': 122, 'r1': 250.0, 'c1': 237.0, 'n': 22884, 'inconsistent': 0}, 'sentences': {'o11': 121, 'r1': 244.5, 'c1': 229.5, 'n': 9227, 'inconsistent': 3}}
INFO 2022-10-04 17:13:19,327: query no. 3
INFO 2022-10-04 17:13:21,180: {'embeddings': {'o11': 0, 'r1': 0.0, 'c1': 0.0, 'n': 0, 'inconsistent': 0}, 'subgraphs': {'o11': 0, 'r1': 0.0, 'c1': 0.0, 'n': 0, 'inconsistent': 0}, 'focus_points': {'o11': 0, 'r1': 0.0, 'c1': 0.0, 'n': 0, 'inconsistent': 0}, 'sentences': {'o11': 0, 'r1': 0.0, 'c1': 0.0, 'n': 0, 'inconsistent': 0}}
INFO 2022-10-04 17:13:21,181: query no. 4
INFO 2022-10-04 17:13:24,281: {'embeddings': {'o11': 3, 'r1': 250.0, 'c1': 306.0, 'n': 22884, 'inconsistent': 0}, 'subgraphs': {'o11': 3, 'r1': 250.0, 'c1': 306.0, 'n': 22884, 'inconsistent': 0}, 'focus_points': {'o11': 3, 'r1': 250.0, 'c1': 306.0, 'n': 22884, 'inconsistent': 0}, 'sentences': {'o11': 3, 'r1': 241.0, 'c1': 270.0, 'n': 9227, 'inconsistent': 10}}
Traceback (most recent call last):
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 215, in <module>
    main()
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 207, in main
    o, e = statistics.get_contingency_table(freq["o11"], freq["r1"], freq["c1"], freq["n"])
  File "/Users/yayamamo/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pareidoscope/utils/statistics.py", line 25, in get_contingency_table
    e[1][1] = r1 * c1 / float(n)
ZeroDivisionError: float division by zero
```
Is there anything that I can work around?

In addition, the other query examples resulted in failure of "KyeError: 'query'"

**Comment by tsproisl** [comment]
The problem lies in query no. 3 for which no results are found. In particular, the sample size N is 0 which leads to the division by zero error. For a quick workaround, I simply removed this particular query from the examples file.

Why are there no results for the query? When it converts the CoNLL-U file into an SQLite database, the Pareidoscope prefers the ninth column for extracting the syntactic relations, i.e. the so-called “enhanced dependency graph”. It seems that this enhanced dependency graph no longer contains the plain nmod relations that are part of the problematic query (or maybe the old version I used only had the dependency tree in the eighth column, which the Pareidoscope falls back to when there are no dependency relations in the ninth column). Instead, there are only collapsed nmod relations, e.g. nmod:of, nmod:for, etc., which the query doesn’t match.

Of course, the proper way of dealing with this would be to inform the user that their query yields no results and to skip this query when computing the association scores (thereby avoiding the division by zero error).

> In addition, the other query examples resulted in failure of "KyeError: 'query'"

All the other query examples (I assume you mean the example JSON files for the other scripts?) should work as expected. For which one do you get an error?

**Comment by yayamamo** [comment]
Thanks for your reply.
I got the following error of "KeyError: 'query'".

```
% pareidoscope_association_strength --format db -o associations en-ud-train.db ./Pareidoscope/doc/ex_associated_structures.json
Traceback (most recent call last):
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 215, in <module>
    main()
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 194, in main
    queries = [extract_graphs(q) for q in queries]
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 194, in <listcomp>
    queries = [extract_graphs(q) for q in queries]
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 62, in extract_graphs
    a = query.subgraph([v for v, l in query.nodes(data=True) if l["query"] == "A" or l["query"] == "AB"]).copy()
  File "/Users/yayamamo/.pyenv/versions/3.10.6/bin/pareidoscope_association_strength", line 62, in <listcomp>
    a = query.subgraph([v for v, l in query.nodes(data=True) if l["query"] == "A" or l["query"] == "AB"]).copy()
KeyError: 'query'
```

**Comment by tsproisl** [comment]
The example query you are using (`ex_associated_structures.json`) is not compatible with `pareidoscope_association_strength`. Try using `pareidoscope_associated_structures`, instead:
```
pareidoscope_associated_structures -o associated_structures en-ud-train.db ./Pareidoscope/doc/ex_associated_structures.json
```

**Comment by yayamamo** [comment]
Thanks. It works. I would appreciate it if you could make a getting started guide.
